/**
 * Telegram inbound media: trust lock parity with text, download-to-media-dir,
 * size caps, the vision-analysis turn composition (caption + clearly marked
 * model description), and the disabled/non-image fallbacks. Driven through
 * TelegramChannel.handleMediaMessage with a structural mock context — no
 * live Bot, no network (fetchFile is injected).
 */
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, it } from 'node:test';
import type { Logger } from 'pino';
import {
  TelegramChannel,
  type TelegramMediaContext,
  type TelegramVisionDeps,
} from '../../src/channels/telegram.js';
import type { InboundMessage } from '../../src/channels/types.js';

const silent = { info() {}, warn() {}, error() {}, debug() {}, child() { return silent; } } as unknown as Logger;

const PNG_BYTES = Buffer.from('89504e470d0a1a0a-fake-image-bytes');

interface Harness {
  channel: TelegramChannel;
  inbound: InboundMessage[];
  mediaDir: string;
  downloads: string[];
}

function makeChannel(opts: {
  vision?: TelegramVisionDeps | 'default';
  maxMediaBytes?: number;
  defaultChatId?: string | null;
  allowedChatIds?: string[];
  mediaDir?: string | null;
} = {}): Harness {
  const mediaDir =
    opts.mediaDir === null ? undefined : (opts.mediaDir ?? mkdtempSync(join(tmpdir(), 'meridian-tg-')));
  const inbound: InboundMessage[] = [];
  const downloads: string[] = [];
  const vision: TelegramVisionDeps | undefined =
    opts.vision === 'default'
      ? {
          analyze: async () => ({
            description: 'Hail bruising visible on the south slope.',
            model: 'anthropic/mock',
          }),
        }
      : opts.vision;
  const channel = new TelegramChannel({
    token: 'tg-test-token',
    defaultChatId: opts.defaultChatId === null ? undefined : (opts.defaultChatId ?? '42'),
    allowedChatIds: opts.allowedChatIds,
    logger: silent,
    mediaDir,
    maxMediaBytes: opts.maxMediaBytes,
    vision,
    fetchFile: async (url: string) => {
      downloads.push(url);
      return PNG_BYTES;
    },
  });
  return { channel, inbound, mediaDir: mediaDir ?? '', downloads };
}

function photoCtx(overrides: Partial<{
  chatId: string;
  caption: string;
  fileSize: number;
  replies: string[];
}> = {}): { ctx: TelegramMediaContext; replies: string[] } {
  const replies = overrides.replies ?? [];
  const ctx: TelegramMediaContext = {
    chat: { id: overrides.chatId ?? '42' },
    from: { username: 'aj' },
    message: {
      caption: overrides.caption,
      photo: [
        { file_id: 'small', file_size: 10 },
        { file_id: 'big', file_size: overrides.fileSize ?? PNG_BYTES.length },
      ],
    },
    getFile: async () => ({
      file_unique_id: 'u1',
      file_size: overrides.fileSize ?? PNG_BYTES.length,
      file_path: 'photos/file_1.jpg',
    }),
    reply: async (text: string) => {
      replies.push(text);
    },
    replyWithChatAction: async () => {},
  };
  return { ctx, replies };
}

async function run(h: Harness, ctx: TelegramMediaContext, reply = 'Understood.'): Promise<void> {
  await h.channel.handleMediaMessage(ctx, async (m) => {
    h.inbound.push(m);
    return reply;
  });
}

describe('telegram media — photo happy path', () => {
  it('downloads to the media dir and feeds caption + marked analysis into the turn', async () => {
    const h = makeChannel({ vision: 'default' });
    const { ctx, replies } = photoCtx({ caption: 'Is this hail damage?' });
    await run(h, ctx, 'Yes — that is hail bruising.');

    assert.equal(h.inbound.length, 1);
    const m = h.inbound[0];
    assert.equal(m.channel, 'telegram');
    assert.equal(m.from, '42');
    // Caption preserved, analysis clearly marked as machine-generated.
    assert.ok(m.text.includes('Is this hail damage?'));
    assert.ok(m.text.includes('automated vision analysis via anthropic/mock'));
    assert.ok(m.text.includes('generated by a model, not written by the sender'));
    assert.ok(m.text.includes('Hail bruising visible on the south slope.'));

    // File landed in the media dir with the downloaded bytes.
    const media = (m.meta as { media: { path: string; kind: string } }).media;
    assert.equal(media.kind, 'photo');
    assert.ok(media.path.startsWith(h.mediaDir));
    assert.ok(existsSync(media.path));
    assert.deepEqual(readFileSync(media.path), PNG_BYTES);

    // Download hit the bot-token file URL; reply went back to the chat.
    assert.match(h.downloads[0], /api\.telegram\.org\/file\/bottg-test-token\/photos\/file_1\.jpg/);
    assert.deepEqual(replies, ['Yes — that is hail bruising.']);
  });

  it('notes the missing caption and survives a vision failure with a fallback marker', async () => {
    const h = makeChannel({
      vision: {
        analyze: async () => {
          throw new Error('provider exploded: 402 openrouter.ai');
        },
      },
    });
    const { ctx } = photoCtx();
    await run(h, ctx);
    assert.equal(h.inbound.length, 1);
    const text = h.inbound[0].text;
    assert.ok(text.includes('sent an image with no caption'));
    assert.ok(text.includes('vision analysis failed'));
    assert.ok(!text.includes('402'), 'raw provider error must not reach the turn');
  });

  it('marks the image as unanalyzed when vision is disabled', async () => {
    const h = makeChannel({ vision: undefined });
    const { ctx } = photoCtx({ caption: 'see attached' });
    await run(h, ctx);
    assert.equal(h.inbound.length, 1);
    assert.ok(h.inbound[0].text.includes('vision analysis is disabled'));
    assert.ok(h.inbound[0].text.includes('see attached'));
  });
});

describe('telegram media — trust lock', () => {
  it('rejects an untrusted chat before any download', async () => {
    const h = makeChannel({ vision: 'default' });
    const { ctx, replies } = photoCtx({ chatId: '999' });
    await run(h, ctx);
    assert.equal(h.inbound.length, 0);
    assert.equal(h.downloads.length, 0);
    assert.ok(replies[0].includes('do not recognize this chat'));
  });

  it('bootstrap: the first media sender locks the chat, like text', async () => {
    const h = makeChannel({ vision: 'default', defaultChatId: '' });
    const first = photoCtx({ chatId: '7' });
    await run(h, first.ctx);
    assert.equal(h.inbound.length, 1, 'first sender is trusted');
    const second = photoCtx({ chatId: '8' });
    await run(h, second.ctx);
    assert.equal(h.inbound.length, 1, 'second chat is rejected after the lock');
    assert.ok(second.replies[0].includes('do not recognize this chat'));
  });
});

describe('telegram media — caps and non-images', () => {
  it('refuses an oversize image without calling the turn', async () => {
    const h = makeChannel({ vision: 'default', maxMediaBytes: 16 });
    const { ctx, replies } = photoCtx({ fileSize: 1024 });
    await run(h, ctx);
    assert.equal(h.inbound.length, 0);
    assert.equal(h.downloads.length, 0);
    assert.ok(replies[0].includes('too large'));
  });

  it('accepts an image document, tags it as document-image', async () => {
    const h = makeChannel({ vision: 'default' });
    const replies: string[] = [];
    const ctx: TelegramMediaContext = {
      chat: { id: '42' },
      from: { username: 'aj' },
      message: {
        caption: 'roof scan',
        document: { file_id: 'd1', file_name: 'roof.png', mime_type: 'image/png', file_size: 64 },
      },
      getFile: async () => ({ file_unique_id: 'u9', file_size: 64, file_path: 'documents/roof.png' }),
      reply: async (t: string) => {
        replies.push(t);
      },
      replyWithChatAction: async () => {},
    };
    await run(h, ctx);
    assert.equal(h.inbound.length, 1);
    const media = (h.inbound[0].meta as { media: { path: string; kind: string } }).media;
    assert.equal(media.kind, 'document-image');
    assert.ok(media.path.endsWith('.png'), 'extension comes from the document file name');
  });

  it('politely declines non-image documents', async () => {
    const h = makeChannel({ vision: 'default' });
    const replies: string[] = [];
    const ctx: TelegramMediaContext = {
      chat: { id: '42' },
      message: {
        document: { file_id: 'd2', file_name: 'notes.pdf', mime_type: 'application/pdf' },
      },
      getFile: async () => ({ file_unique_id: 'u2', file_path: 'documents/notes.pdf' }),
      reply: async (t: string) => {
        replies.push(t);
      },
      replyWithChatAction: async () => {},
    };
    await run(h, ctx);
    assert.equal(h.inbound.length, 0);
    assert.ok(replies[0].includes('only view images'));
  });
});

describe('telegram multi-chat trust', () => {
  it('accepts every chat in allowedChatIds, not just defaultChatId', async () => {
    const h = makeChannel({ vision: 'default', allowedChatIds: ['777', '-100888'] });
    for (const chatId of ['42', '777', '-100888']) {
      const { ctx } = photoCtx({ chatId });
      await run(h, ctx);
    }
    assert.equal(h.inbound.length, 3, 'operator DM, client DM, and group all reach the turn');
  });

  it('refuses a chat outside the trusted set and never runs the turn', async () => {
    const h = makeChannel({ vision: 'default', allowedChatIds: ['777'] });
    const { ctx, replies } = photoCtx({ chatId: '999' });
    await run(h, ctx);
    assert.equal(h.inbound.length, 0);
    assert.ok(replies.some((r) => /do not recognize this chat/.test(r)));
  });

  it('configured chats disable the bootstrap lock — a stranger cannot claim trust', async () => {
    const h = makeChannel({ vision: 'default', defaultChatId: null, allowedChatIds: ['777'] });
    const stranger = photoCtx({ chatId: '999' });
    await run(h, stranger.ctx);
    assert.equal(h.inbound.length, 0, 'stranger refused even though defaultChatId is unset');
    const trusted = photoCtx({ chatId: '777' });
    await run(h, trusted.ctx);
    assert.equal(h.inbound.length, 1);
  });

  it('bootstrap still locks the first sender when nothing is configured', async () => {
    const h = makeChannel({ vision: 'default', defaultChatId: null });
    const first = photoCtx({ chatId: '555' });
    await run(h, first.ctx);
    assert.equal(h.inbound.length, 1, 'first sender locks and is served');
    const second = photoCtx({ chatId: '999' });
    await run(h, second.ctx);
    assert.equal(h.inbound.length, 1, 'later stranger refused');
  });
});
